---
- name: Install and Configure Console
  hosts: [consul_nodes]
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: yes

  vars:
    ansible_ssh_private_key_file: "{{ lookup('env','SSH_KEYDIR') }}"
  roles:
    - {role: consul}
